Add React media components
team-telnyx/webrtc pull request #57
Opened 2020-11-11 23:52 UTC by SuaYoo

Describe your changes

## 📝 To Do

- [ ] All linters pass
- [ ] All tests pass
- [ ] Change documentation based on my changes

## ✋ Manual testing

1. Provide manual testing instructions

## 🦊 Browser testing

### Desktop

- [ ] Edge (latest)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

## 📸 Screenshots

| Description | Screenshot |
| ----------- | ---------- |
| Desktop     |            |
| usage.gif   |            |

2020-11-12 22:13 UTC, hugobdev approved these changes
Great examples and Media component

2020-11-13 13:37 UTC, DeividVeloso requested changes
I tested and the audio is opened(I mean you can hear your voice) before the callee pick up the call.

I think you can add this script command ` "setup": "cp .env.sample .env"`

2020-11-17 23:07 UTC, SuaYoo commented
> I tested and the audio is opened(I mean you can hear your voice) before the callee pick up the call.
@DeividVeloso I fixed the doubled audio issue by tweaking the UX by adding a checkbox:
<img width="217" alt="Screen Shot 2020-11-17 at 3 06 59 PM" src="https://user-images.githubusercontent.com/4672952/99461381-973eda80-28e6-11eb-8518-29bd046f552e.png">
Could you retest?

2020-11-18 12:49 UTC, DeividVeloso approved these changes

2020-11-18 17:29 UTC, merged