feat(WEBRTC-234): add typedoc on setVideoSettings method
team-telnyx/webrtc pull request #74
Opened 2020-11-30 16:02 UTC by DeividVeloso

- add typedoc on setVideoSettings method

## 📝 To Do

- [x] All linters pass
- [ ] All tests pass
- [ ] Change documentation based on my changes

## ✋ Manual testing

1. Provide manual testing instructions

## 🦊 Browser testing

### Desktop

- [ ] Edge (latest)
- [x] Chrome
- [ ] Firefox
- [ ] Safari

## 📸 Screenshots

| Description | Screenshot |
| ----------- | ---------- |
| Desktop     |![image](https://user-images.githubusercontent.com/16343871/100632914-2b0f9e00-330c-11eb-8d4e-6505d5c9e456.png)|

2020-12-02 15:35 UTC, hugobdev requested changes

2020-12-02 15:35 UTC, hugobdev commented on packages/js/src/Modules/Verto/BrowserSession.ts
> +   * You can set the default `audio` constraints for your client. [See here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_audio_tracks) for further details.
```suggestion
   * Sets the default `audio` constraints for your client. [See here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_audio_tracks) for further details.
```

2020-12-02 15:35 UTC, hugobdev commented on packages/js/src/Modules/Verto/BrowserSession.ts
> +   * You can set the default `audio` constraints for your client. [See here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_audio_tracks) for further details.
Again, we should keep docs in the infinitive.

2020-12-02 15:35 UTC, hugobdev commented on packages/js/src/Modules/Verto/BrowserSession.ts
> +   * You can set the default `video` constraints for your client. [See here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_video_tracks) for further details.
```suggestion
   * Sets the default `video` constraints for your client. [See here](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#Properties_of_video_tracks) for further details.
```

2020-12-02 17:49 UTC, SuaYoo reviewed
Did you mean to branch this from https://github.com/team-telnyx/webrtc/pull/73 ? Looks like there is duplicate changes

2020-12-02 18:09 UTC, DeividVeloso commented
> Did you mean to branch this from #73 ? Looks like there is duplicate changes

I cloned from #73, because the code is pretty equal, we need to merge 73 first.

2020-12-02 22:08 UTC, SuaYoo commented
> > Did you mean to branch this from #73 ? Looks like there is duplicate changes
> 
> I cloned from #73, because the code is pretty equal, we need to merge 73 first.

I see your changes in #73 in this PR when I look at the files changed. I tried changing the base, but it looks like you may have accidentally copied `setAudioSettings` altogether and will need to delete those lines from this PR.

2020-12-02 22:09 UTC, SuaYoo commented on packages/js/examples/react-audio/stories/components/Utilities.js
> +  };
This is the duplicated code from https://github.com/team-telnyx/webrtc/pull/73/files

2020-12-02 22:09 UTC, SuaYoo commented on packages/js/src/Modules/Verto/BrowserSession.ts
> +   */
This as well: https://github.com/team-telnyx/webrtc/pull/73/files#diff-2447a25963f6b87422abbb0c3432ebcd9ebaf2c4e9abef301057d962b60a45b6

2020-12-03 19:34 UTC, hugobdev approved these changes

2020-12-03 19:43 UTC, merged